module Petals
  class Viewport
    def initialize: (?width: Integer, ?height: Integer) -> void
    def set_content: (String content) -> void
    def set_width: (Integer w) -> void
    def set_height: (Integer h) -> void
    def scroll_to: (Integer line) -> void
    def scroll_by: (Integer delta) -> void
    def update: (untyped msg) -> untyped?
    def view: () -> String
  end
end
